"""
services/reasoning_model.py
===========================
Reasoning client — generates image-generation prompts from a validated brief.
Called by node_reasoning() in agent.py.

Default provider : AWS Bedrock (Claude Sonnet)
Swap provider    : pass any ModelProvider instance to __init__
"""

from __future__ import annotations

import json
import logging
import re
from typing import Any, Dict, Optional
from venv import logger

from backend.services.providers.model_provider import ModelProvider
from backend.services.providers.openroute_provider import OpenRouterProvider
from backend.services.providers.bedrock_provider import BedrockProvider, CLAUDE_SONNET
from backend.logger import logger


SYSTEM_PROMPT = """You are an expert creative director and prompt engineer for AI image generation.

Given a creative brief, generate 1-4 detailed image-generation prompts that STRICTLY follow every requirement.

RULES:
- Every visual, text, CTA, pricing, headline, subheading instruction from the brief MUST appear verbatim in the prompt.
- Text overlays must be written exactly as: 'headline text: "Mega Sale"', 'subheading: "Sales"', 'CTA: "Order Now"', 'price text: "Starting from $200"'
- Never skip, summarize, or paraphrase client text requirements.
- Match the exact number of concepts the brief asks for.
- Include: subject, style, lighting, mood, color, composition, text overlays, quality keywords.
- Append negative prompt after " | negative: ".

EXAMPLE:
Brief says: "headline - Mega Sale, sub heading - sales, pricing starting from $200, CTA - order now"
Your prompt MUST contain: 'bold headline text "Mega Sale" in upper area, subheading "Sales" below it, price text "Starting from $200" in mid-lower area, CTA "Order Now" at bottom'

Respond ONLY with valid JSON:
{
  "prompts": [
    {
      "index":        0,
      "description":  "<short label>",
      "positive":     "<full prompt with ALL brief requirements including verbatim text>",
      "negative":     "<negative prompt>",
      "full_prompt":  "<positive> | negative: <negative>",
      "aspect_ratio": "1:1"
    }
  ]
}"""


class ReasoningClient:
    """
    Generates image-generation prompts from the validated brief + tags.

    Args:
        provider: Any ModelProvider instance.
                  Default: BedrockProvider with Claude Sonnet.
                  Swap to OpenRouterProvider or any other with zero changes to agent.py.

    Usage in agent.py:
        result = reasoning_client.generate_prompts(context)
        # {"prompts": [str, ...]}

    Swap provider example:
        from src.providers.openrouter_provider import OpenRouterProvider
        reasoning = ReasoningClient(provider=OpenRouterProvider(model_id="anthropic/claude-sonnet-4"))
    """

    def __init__(self, provider: Optional[OpenRouterProvider] = None):
        self.provider = provider or BedrockProvider(model_id=CLAUDE_SONNET,region="us-east-1", max_tokens=2048)
        logger.info(f"ReasoningClient initialised  provider={self.provider.model_name}")

    # ── Called by node_reasoning() ────────────────────────────────────────────

    def generate_prompts(self, context: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generate image-generation prompts from the validated brief.

        Args:
            context: From BriefManager.get_reasoning_context()
                {
                  "chat_id":  str,
                  "task":     "generate_image_prompts",
                  "elements": [...],
                  "tags":     [...],
                }

        Returns:
            {"prompts": [str, ...]}   ← flat list of full_prompt strings
                                        ready for ImageClient.generate()
        """
        logger.info(f"ReasoningClient.generate_prompts  chat_id={context.get('chat_id')}  tags={len(context.get('tags', []))}")
        logger.info(f"Raw Conext for ReasoningClient:\n{context}\n")
        prompt  = self._build_prompt(context)
        logger.info(f"ReasoningClient: sending prompt to model provider:\n{prompt}\n")
        raw     = self.provider.generate(prompt, options={"system": SYSTEM_PROMPT, "max_tokens": 2048})
        parsed  = self._parse_response(raw)

        # Extract flat list of full_prompt strings for BriefManager / agent
        prompt_objects = parsed.get("prompts", [])
        flat_prompts   = [p.get("full_prompt", p.get("positive", "")) for p in prompt_objects]


        logger.info(f"ReasoningClient: generated {len(flat_prompts)} prompt(s)")
        logger.info(f"raw prompt generated by reasoning model: {raw}  ")
        return {"prompts": flat_prompts, "prompt_objects": prompt_objects}

    # ── Internal ──────────────────────────────────────────────────────────────

    def _build_prompt(self, context):
        prev = context.get("prev_prompt", "")
        if prev:
            return (
                f"You are modifying an existing image. "
                f"Here is the previous prompt that generated the image:\n\n"
                f"{prev}\n\n"
                f"Apply ONLY this modification to it:\n\n"
                f"{context.get('raw_input', '')}\n\n"
                f"Return a new full prompt with the modification applied. Keep everything else identical."
            )
        return (
            f"Generate image prompts for this creative brief:\n\n"
            f"{context.get('raw_input', '')}"
        )

    def _parse_response(self, raw: str) -> Dict[str, Any]:
        cleaned = re.sub(r"```(?:json)?|```", "", raw).strip()
        try:
            return json.loads(cleaned)
        except json.JSONDecodeError:
            logger.warning("ReasoningClient: response is not valid JSON — returning fallback")
            # Try to recover any long quoted strings as prompts
            fallback = re.findall(r'"([^"]{30,})"', raw)
            return {"prompts": [{"index": i, "full_prompt": p, "positive": p, "negative": ""} for i, p in enumerate(fallback[:4])]}